export const actions = {
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    INCREASE_QUANTITY:"INCREASE_QUANTITY",
    DECREASE_QUANTITY:"DECREASE_QUANTITY",
    EMPTY_CART:"EMPTY_CART",
    CHECKOUT:"CHECKOUT",
    PLACE_ORDER:"PLACE_ORDER",
    EMPTY_ORDER:"EMPTY_ORDER"
}